const data = [
    {
        id: 1,
        orderNumber: 1,
        orderDate: "13/12/2020",
        orderBuyer: "Jack Martin",
        status: "awaiting",
        supplier: "asy",
        orderName: "necklace",
        orderLength: "30cm",
        orderColor: "silver",
        qty: "1",
        size: "5mm",
        start: "middle",
        gap: "adjacent",
        ready: false,
        explanation: "SAM",
        personalization: "SAM",
        cNote: ""

    },
    {
        id: 2,
        orderNumber: 2,
        orderDate: "27/12/2020",
        orderBuyer: "Joe Denis",
        status: "sent",
        supplier: "asy",
        orderName: "wristband",
        orderLength: "16cm",
        orderColor: "rose",
        qty: "2",
        size: "3cm",
        start: "middle",
        gap: "",
        ready: true,
        explanation: "TONI",
        personalization: "TONI",
        cNote: "",

    },
    {
        id: 3,
        orderNumber: 3,
        orderDate: "16/12/2020",
        orderBuyer: "Jane Martin",
        status: "awaiting",
        supplier: "asy",
        orderName: "necklace",
        orderLength: "30cm",
        orderColor: "silver",
        qty: "1",
        size: "5mm",
        start: "middle",
        gap: "adjacent",
        ready: true,
        explanation: "SAM",
        personalization: "SAM",
        cNote: ""

    },
    {
        id: 4,
        orderNumber: 4,
        orderDate: "27/12/2020",
        orderBuyer: "John Denis",
        status: "sent",
        supplier: "asy",
        orderName: "wristband",
        orderLength: "16cm",
        orderColor: "rose",
        qty: "2",
        size: "3cm",
        start: "middle",
        gap: "",
        ready: true,
        explanation: "TONI",
        personalization: "TONI",
        cNote: "",

    },
    {
        id: 5,
        orderNumber: 5,
        orderDate: "13/12/2020",
        orderBuyer: "Jack Martin",
        status: "sent",
        supplier: "asy",
        orderName: "necklace",
        orderLength: "30cm",
        orderColor: "silver",
        qty: "1",
        size: "5mm",
        start: "middle",
        gap: "adjacent",
        ready: false,
        explanation: "SAM",
        personalization: "SAM",
        cNote: ""

    },
    {
        id: 6,
        orderNumber: 6,
        orderDate: "27/12/2020",
        orderBuyer: "Joe Denis",
        status: "sent",
        supplier: "asy",
        orderName: "wristband",
        orderLength: "16cm",
        orderColor: "rose",
        qty: "2",
        size: "3cm",
        start: "middle",
        gap: "",
        ready: true,
        explanation: "TONI",
        personalization: "TONI",
        cNote: "",

    },
    {
        id: 7,
        orderNumber: 7,
        orderDate: "13/12/2020",
        orderBuyer: "Jack Martin",
        status: "awaiting",
        supplier: "asy",
        orderName: "necklace",
        orderLength: "30cm",
        orderColor: "silver",
        qty: "1",
        size: "5mm",
        start: "middle",
        gap: "adjacent",
        ready: false,
        explanation: "SAM",
        personalization: "SAM",
        cNote: ""

    },
    {
        id: 8,
        orderNumber: 8,
        orderDate: "27/12/2020",
        orderBuyer: "Joe Denis",
        status: "awaiting",
        supplier: "asy",
        orderName: "wristband",
        orderLength: "16cm",
        orderColor: "rose",
        qty: "2",
        size: "3cm",
        start: "middle",
        gap: "",
        ready: true,
        explanation: "TONI",
        personalization: "TONI",
        cNote: "",

    },
]

export default data;